version: "3.3"

services:
  postgres_service:
    container_name: postgres_service_2
    image: postgres:12.14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wine
    restart: on-failure
    networks:
      - elt-network             # postgres joins this network

  mage:
    image: mageai/mageai:0.9.64          
    container_name: elt_mage_pipeline
    command: ["mage", "start", "mage_project"]   
    ports:
      - "7801:6789"                                 
    volumes:
      - ./:/home/src       
    environment:
      - REQUIRE_USER_AUTHENTICATION=1            
    restart: on-failure
    depends_on:
      - postgres_service
    networks:
      - elt-network       # postgres joins this network

networks:
  elt-network:
    driver: bridge